### ISSUE TITLE
CI/CDワークフロー構築

### ISSUE THREAD

**Issue by Mizuha-hk** [Mizuha-hk/ConsoleOthello#5]
## 概要
#2 で作成したテストの実行(CI)とコンソールアプリのrelease(CD)を行うワークフロー構築
## 作業内容
- [x] 要件定義
- [ ] 実装

**Comment by Mizuha-hk** [comment]
## CIの実行条件
プッシュ時
## CDの実行条件
masterマージ時

**Comment by Mizuha-hk** [comment]
## GitHub Copilotの回答

.NET 9のコンソールアプリ向けのCI/CDワークフローを作成します。まず、現在のリポジトリ構造を確認してから、適切なワークフローファイルを提案させていただきます。プロジェクト構造を確認しました。.NET 9のコンソールアプリケーションとテストプロジェクトが存在していることが分かりました。

以下、CI/CDワークフローの構築について詳細に説明します：

## 1. ワークフローファイルの作成

`.github/workflows/ci-cd.yml` ファイルを作成します：

```yaml name=.github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ "*" ]  # 任意のブランチにプッシュ時
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # 手動実行を可能にする

env:
  DOTNET_VERSION: '9.0.x'
  PROJECT_NAME: 'OthelloApp.ConsoleApp'
  TEST_PROJECT: 'OthelloApp.Core.Test'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build solution
      run: dotnet build --no-restore --configuration Release
      
    - name: Run tests
      run: dotnet test --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage"
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: "**/TestResults/**/*"

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 全履歴を取得してタグ情報を取得
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Get version from project file
      id: get_version
      run: |
        VERSION=$(grep '<Version>' OthelloApp.Console/OthelloApp.ConsoleApp.csproj | sed 's/.*<Version>\(.*\)<\/Version>.*/\1/' || echo "1.0.0")
        if [ "$VERSION" = "1.0.0" ]; then
          # Versionタグがない場合は日付ベースのバージョンを生成
          VERSION="1.0.$(date +'%Y%m%d')-$(echo $GITHUB_SHA | cut -c1-7)"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
        
    - name: Build for multiple platforms
      run: |
        # Windows x64
        dotnet publish OthelloApp.Console/OthelloApp.ConsoleApp.csproj \
          -c Release \
          -r win-x64 \
          --self-contained true \
          -p:PublishSingleFile=true \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          -o ./publish/win-x64
          
        # Linux x64
        dotnet publish OthelloApp.Console/OthelloApp.ConsoleApp.csproj \
          -c Release \
          -r linux-x64 \
          --self-contained true \
          -p:PublishSingleFile=true \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          -o ./publish/linux-x64
          
        # macOS x64
        dotnet publish OthelloApp.Console/OthelloApp.ConsoleApp.csproj \
          -c Release \
          -r osx-x64 \
          --self-contained true \
          -p:PublishSingleFile=true \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          -o ./publish/osx-x64
          
    - name: Create release archives
      run: |
        cd publish
        
        # Windows
        zip -r ../OthelloApp-${{ steps.get_version.outputs.version }}-win-x64.zip win-x64/
        
        # Linux
        tar -czf ../OthelloApp-${{ steps.get_version.outputs.version }}-linux-x64.tar.gz linux-x64/
        
        # macOS
        tar -czf ../OthelloApp-${{ steps.get_version.outputs.version }}-osx-x64.tar.gz osx-x64/
        
        cd ..
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        release_name: Release v${{ steps.get_version.outputs.version }}
        body: |
          ## Changes
          
          - Auto-generated release from master branch
          - Commit: ${{ github.sha }}
          
          ## Downloads
          
          - Windows x64: `OthelloApp-${{ steps.get_version.outputs.version }}-win-x64.zip`
          - Linux x64: `OthelloApp-${{ steps.get_version.outputs.version }}-linux-x64.tar.gz`
          - macOS x64: `OthelloApp-${{ steps.get_version.outputs.version }}-osx-x64.tar.gz`
        draft: false
        prerelease: false
        
    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./OthelloApp-${{ steps.get_version.outputs.version }}-win-x64.zip
        asset_name: OthelloApp-${{ steps.get_version.outputs.version }}-win-x64.zip
        asset_content_type: application/zip
        
    - name: Upload Linux Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./OthelloApp-${{ steps.get_version.outputs.version }}-linux-x64.tar.gz
        asset_name: OthelloApp-${{ steps.get_version.outputs.version }}-linux-x64.tar.gz
        asset_content_type: application/gzip
        
    - name: Upload macOS Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./OthelloApp-${{ steps.get_version.outputs.version }}-osx-x64.tar.gz
        asset_name: OthelloApp-${{ steps.get_version.outputs.version }}-osx-x64.tar.gz
        asset_content_type: application/gzip
```

## 2. プロジェクトファイルの更新

バージョン管理のため、プロジェクトファイルにバージョン情報を追加することをお勧めします：

```xml name=OthelloApp.Console/OthelloApp.ConsoleApp.csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Product>OthelloApp Console</Product>
    <Description>Console Othello Game Application</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OthelloApp.Core\OthelloApp.Core.csproj" />
  </ItemGroup>

</Project>
```

## 3. GitHub側での設定・考慮事項

### リポジトリ設定
1. **Actions権限の確認**
   - Settings > Actions > General で「Allow all actions and reusable workflows」が有効になっていることを確認

2. **Secrets設定**
   - `GITHUB_TOKEN`は自動的に利用可能ですが、追加のトークンが必要な場合は Settings > Secrets and variables > Actions で設定

### ブランチ戦略
1. **保護ルール設定**
   ```
   Settings > Branches > Add rule
   - Branch name pattern: master (または main)
   - Require status checks to pass before merging: ✓
   - Require branches to be up to date before merging: ✓
   - Status checks: test job
   ```

2. **推奨ブランチ構成**
   ```
   master (または main) ← リリースブランチ
   ├── develop ← 開発統合ブランチ
   ├── feature/xxx ← 機能開発ブランチ
   └── hotfix/xxx ← 緊急修正ブランチ
   ```

### 追加検討事項

1. **Code Coverage レポート** (オプション)
```yaml name=.github/workflows/coverage.yml
# test jobに追加
- name: Generate coverage report
  run: |
    dotnet test --no-build --configuration Release \
      --collect:"XPlat Code Coverage" \
      --results-directory ./coverage

- name: Upload coverage to Codecov
  uses: codecov/codecov-action@v3
  with:
    directory: ./coverage
```

2. **Dependabot設定**
```yaml name=.github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
```

3. **Issue/PRテンプレート**
```markdown name=.github/pull_request_template.md
## 概要
<!-- 変更内容の概要を記載 -->

## 変更点
- [ ] 機能追加
- [ ] バグ修正
- [ ] リファクタリング
- [ ] ドキュメント更新

## テスト
- [ ] 新しいテストを追加した
- [ ] 既存のテストが通ることを確認した

## チェックリスト
- [ ] コードレビューの準備ができている
- [ ] ドキュメントを更新した（必要に応じて）
```

このワークフローにより、任意のブランチへのプッシュでテストが実行され、masterブランチへのマージ時に自動的にGitHub Releaseが作成されます。
